/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StockroomRouteImport } from './routes/stockroom'
import { Route as SellRouteImport } from './routes/sell'
import { Route as RetailRouteImport } from './routes/retail'
import { Route as RefurbishersRouteImport } from './routes/refurbishers'
import { Route as PulseRouteImport } from './routes/pulse'
import { Route as ProvenanceRouteImport } from './routes/provenance'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PhoneCheckRouteImport } from './routes/phone-check'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as FlowRouteImport } from './routes/flow'
import { Route as CustomerBuybackTemplateRouteImport } from './routes/customer-buyback-template'
import { Route as BuybackRouteImport } from './routes/buyback'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnterpriseIndexRouteImport } from './routes/enterprise/index'
import { Route as EnterprisePricerRouteImport } from './routes/enterprise/pricer'
import { Route as EnterpriseContactRouteImport } from './routes/enterprise/contact'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const StockroomRoute = StockroomRouteImport.update({
  id: '/stockroom',
  path: '/stockroom',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const RetailRoute = RetailRouteImport.update({
  id: '/retail',
  path: '/retail',
  getParentRoute: () => rootRouteImport,
} as any)
const RefurbishersRoute = RefurbishersRouteImport.update({
  id: '/refurbishers',
  path: '/refurbishers',
  getParentRoute: () => rootRouteImport,
} as any)
const PulseRoute = PulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvenanceRoute = ProvenanceRouteImport.update({
  id: '/provenance',
  path: '/provenance',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneCheckRoute = PhoneCheckRouteImport.update({
  id: '/phone-check',
  path: '/phone-check',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowRoute = FlowRouteImport.update({
  id: '/flow',
  path: '/flow',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerBuybackTemplateRoute = CustomerBuybackTemplateRouteImport.update({
  id: '/customer-buyback-template',
  path: '/customer-buyback-template',
  getParentRoute: () => rootRouteImport,
} as any)
const BuybackRoute = BuybackRouteImport.update({
  id: '/buyback',
  path: '/buyback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseIndexRoute = EnterpriseIndexRouteImport.update({
  id: '/enterprise/',
  path: '/enterprise/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterprisePricerRoute = EnterprisePricerRouteImport.update({
  id: '/enterprise/pricer',
  path: '/enterprise/pricer',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseContactRoute = EnterpriseContactRouteImport.update({
  id: '/enterprise/contact',
  path: '/enterprise/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buyback': typeof BuybackRoute
  '/customer-buyback-template': typeof CustomerBuybackTemplateRoute
  '/flow': typeof FlowRoute
  '/integrations': typeof IntegrationsRoute
  '/mcp': typeof McpRoute
  '/phone-check': typeof PhoneCheckRoute
  '/pricing': typeof PricingRoute
  '/provenance': typeof ProvenanceRoute
  '/pulse': typeof PulseRoute
  '/refurbishers': typeof RefurbishersRoute
  '/retail': typeof RetailRoute
  '/sell': typeof SellRoute
  '/stockroom': typeof StockroomRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/enterprise/contact': typeof EnterpriseContactRoute
  '/enterprise/pricer': typeof EnterprisePricerRoute
  '/enterprise/': typeof EnterpriseIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buyback': typeof BuybackRoute
  '/customer-buyback-template': typeof CustomerBuybackTemplateRoute
  '/flow': typeof FlowRoute
  '/integrations': typeof IntegrationsRoute
  '/mcp': typeof McpRoute
  '/phone-check': typeof PhoneCheckRoute
  '/pricing': typeof PricingRoute
  '/provenance': typeof ProvenanceRoute
  '/pulse': typeof PulseRoute
  '/refurbishers': typeof RefurbishersRoute
  '/retail': typeof RetailRoute
  '/sell': typeof SellRoute
  '/stockroom': typeof StockroomRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/enterprise/contact': typeof EnterpriseContactRoute
  '/enterprise/pricer': typeof EnterprisePricerRoute
  '/enterprise': typeof EnterpriseIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buyback': typeof BuybackRoute
  '/customer-buyback-template': typeof CustomerBuybackTemplateRoute
  '/flow': typeof FlowRoute
  '/integrations': typeof IntegrationsRoute
  '/mcp': typeof McpRoute
  '/phone-check': typeof PhoneCheckRoute
  '/pricing': typeof PricingRoute
  '/provenance': typeof ProvenanceRoute
  '/pulse': typeof PulseRoute
  '/refurbishers': typeof RefurbishersRoute
  '/retail': typeof RetailRoute
  '/sell': typeof SellRoute
  '/stockroom': typeof StockroomRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/enterprise/contact': typeof EnterpriseContactRoute
  '/enterprise/pricer': typeof EnterprisePricerRoute
  '/enterprise/': typeof EnterpriseIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/buyback'
    | '/customer-buyback-template'
    | '/flow'
    | '/integrations'
    | '/mcp'
    | '/phone-check'
    | '/pricing'
    | '/provenance'
    | '/pulse'
    | '/refurbishers'
    | '/retail'
    | '/sell'
    | '/stockroom'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/enterprise/contact'
    | '/enterprise/pricer'
    | '/enterprise/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/buyback'
    | '/customer-buyback-template'
    | '/flow'
    | '/integrations'
    | '/mcp'
    | '/phone-check'
    | '/pricing'
    | '/provenance'
    | '/pulse'
    | '/refurbishers'
    | '/retail'
    | '/sell'
    | '/stockroom'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/enterprise/contact'
    | '/enterprise/pricer'
    | '/enterprise'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/buyback'
    | '/customer-buyback-template'
    | '/flow'
    | '/integrations'
    | '/mcp'
    | '/phone-check'
    | '/pricing'
    | '/provenance'
    | '/pulse'
    | '/refurbishers'
    | '/retail'
    | '/sell'
    | '/stockroom'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/enterprise/contact'
    | '/enterprise/pricer'
    | '/enterprise/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BuybackRoute: typeof BuybackRoute
  CustomerBuybackTemplateRoute: typeof CustomerBuybackTemplateRoute
  FlowRoute: typeof FlowRoute
  IntegrationsRoute: typeof IntegrationsRoute
  McpRoute: typeof McpRoute
  PhoneCheckRoute: typeof PhoneCheckRoute
  PricingRoute: typeof PricingRoute
  ProvenanceRoute: typeof ProvenanceRoute
  PulseRoute: typeof PulseRoute
  RefurbishersRoute: typeof RefurbishersRoute
  RetailRoute: typeof RetailRoute
  SellRoute: typeof SellRoute
  StockroomRoute: typeof StockroomRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  EnterpriseContactRoute: typeof EnterpriseContactRoute
  EnterprisePricerRoute: typeof EnterprisePricerRoute
  EnterpriseIndexRoute: typeof EnterpriseIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stockroom': {
      id: '/stockroom'
      path: '/stockroom'
      fullPath: '/stockroom'
      preLoaderRoute: typeof StockroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retail': {
      id: '/retail'
      path: '/retail'
      fullPath: '/retail'
      preLoaderRoute: typeof RetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refurbishers': {
      id: '/refurbishers'
      path: '/refurbishers'
      fullPath: '/refurbishers'
      preLoaderRoute: typeof RefurbishersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulse': {
      id: '/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof PulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provenance': {
      id: '/provenance'
      path: '/provenance'
      fullPath: '/provenance'
      preLoaderRoute: typeof ProvenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone-check': {
      id: '/phone-check'
      path: '/phone-check'
      fullPath: '/phone-check'
      preLoaderRoute: typeof PhoneCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow': {
      id: '/flow'
      path: '/flow'
      fullPath: '/flow'
      preLoaderRoute: typeof FlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-buyback-template': {
      id: '/customer-buyback-template'
      path: '/customer-buyback-template'
      fullPath: '/customer-buyback-template'
      preLoaderRoute: typeof CustomerBuybackTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyback': {
      id: '/buyback'
      path: '/buyback'
      fullPath: '/buyback'
      preLoaderRoute: typeof BuybackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise/': {
      id: '/enterprise/'
      path: '/enterprise'
      fullPath: '/enterprise/'
      preLoaderRoute: typeof EnterpriseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise/pricer': {
      id: '/enterprise/pricer'
      path: '/enterprise/pricer'
      fullPath: '/enterprise/pricer'
      preLoaderRoute: typeof EnterprisePricerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise/contact': {
      id: '/enterprise/contact'
      path: '/enterprise/contact'
      fullPath: '/enterprise/contact'
      preLoaderRoute: typeof EnterpriseContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BuybackRoute: BuybackRoute,
  CustomerBuybackTemplateRoute: CustomerBuybackTemplateRoute,
  FlowRoute: FlowRoute,
  IntegrationsRoute: IntegrationsRoute,
  McpRoute: McpRoute,
  PhoneCheckRoute: PhoneCheckRoute,
  PricingRoute: PricingRoute,
  ProvenanceRoute: ProvenanceRoute,
  PulseRoute: PulseRoute,
  RefurbishersRoute: RefurbishersRoute,
  RetailRoute: RetailRoute,
  SellRoute: SellRoute,
  StockroomRoute: StockroomRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  EnterpriseContactRoute: EnterpriseContactRoute,
  EnterprisePricerRoute: EnterprisePricerRoute,
  EnterpriseIndexRoute: EnterpriseIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
